# Working directories

The working directory is the default location where R will look for files you want to load and where it will put any files you save.

You can also use the `getwd()` function in the Console which returns the file path of the current working directory.

In [33]:
getwd()

[1] "/Users/danielbustos/Library/CloudStorage/Dropbox/UCM/Doctorado_Ingenieria/Clases/R/Import_Data"

If you wanna set a directory

In [34]:
setwd('/Users/danielbustos/Library/CloudStorage/Dropbox/UCM/Doctorado_Ingenieria/Clases/R/Import_Data')

In [35]:
getwd()

[1] "/Users/danielbustos/Library/CloudStorage/Dropbox/UCM/Doctorado_Ingenieria/Clases/R/Import_Data"

If you wanna list the files located into the directory

In [36]:
list.files()

[1] "Canserbero_lyrics.txt"     "Import_data_R.ipynb"
[3] "hotel_bookings_clean.csv"  "hotel_bookings_clean.xlsx"
[5] "notebook.ipynb"

# Importing data in R

Loading data into R can be quite frustrating. Almost every single type of file that you want to get into R seems to require its function, and even then, you might get lost in the functions’ arguments. In short, it can be fairly easy to mix up things from time to time, whether you are a beginner or a more advanced R user.

## Importing data to R from a CSV files

### readr() function

In this section, we will read data in r by loading a CSV file from Hotel Booking Demand. This dataset consists of booking data from a city hotel and a resort hotel. To import the CSV file, we will use the readr package’s `read_csv` function.

readr supports the following file formats with these read_*() functions:

read_csv(): comma-separated values (CSV)

read_tsv(): tab-separated values (TSV)

read_csv2(): semicolon-separated values with , as the decimal mark

read_delim(): delimited files (CSV and TSV are important special cases)

read_fwf(): fixed-width files

read_table(): whitespace-separated files

read_log(): web log files

In [17]:
library(readr)

data1 <- read_csv('hotel_bookings_clean.csv', show_col_types = FALSE)
head(data1)

  is_canceled lead_time arrival_date_week_number arrival_date_day_of_month
1 0           342       27                       1
2 0           737       27                       1
3 0             7       27                       1
4 0            13       27                       1
5 0            14       27                       1
6 0            14       27                       1
  arrival_date_month stays_in_weekend_nights stays_in_week_nights adults
1 7                  0                       0                    2
2 7                  0                       0                    2
3 7                  0                       1                    1
4 7                  0                       1                    1
5 7                  0                       2                    2
6 7                  0                       2                    2
  children babies ⋯ reserved_room_type_G reserved_room_type_H
1 0        0      ⋯ 0                    0
2 0        0      ⋯ 0                    0
3 0        0      ⋯ 0                    0
4 0        0      ⋯ 0                    0
5 0        0      ⋯ 0                    0
6 0        0      ⋯ 0                    0
  reserved_room_type_L deposit_type_No_Deposit deposit_type_Non_Refund
1 0                    1                       0
2 0                    1                       0
3 0                    1                       0
4 0                    1                       0
5 0                    1                       0
6 0                    1                       0
  deposit_type_Refundable customer_type_Contract customer_type_Group
1 0                       0                      0
2 0                       0                      0
3 0                       0                      0
4 0                       0                      0
5 0                       0                      0
6 0                       0                      0
  customer_type_Transient customer_type_Transient-Party
1 1                       0
2 1                       0
3 1                       0
4 1                       0
5 1                       0
6 1                       0

In [9]:
?read_csv()

`read_csv()` and `read_tsv()` are special cases of the more general `read_delim()`. They're useful for reading the most common types of flat file data, comma separated values and tab separated values, respectively. `read_csv2()` uses ⁠;⁠ for the field separator and ⁠,⁠ for the decimal point.

In [23]:
library(readr)

data_tab <- read_delim('hotel_bookings_clean.csv', delim = ',', show_col_types = FALSE)

data_tab

       is_canceled lead_time arrival_date_week_number arrival_date_day_of_month
1      0           342       27                       1
2      0           737       27                       1
3      0             7       27                       1
4      0            13       27                       1
5      0            14       27                       1
6      0            14       27                       1
7      0             0       27                       1
8      0             9       27                       1
9      1            85       27                       1
10     1            75       27                       1
11     1            23       27                       1
12     0            35       27                       1
13     0            68       27                       1
14     0            18       27                       1
15     0            37       27                       1
16     0            68       27                       1
17     0            37       27                       1
18     0            12       27                       1
19     0             0       27                       1
20     0             7       27                       1
21     0            37       27                       1
22     0            72       27                       1
23     0            72       27                       1
24     0            72       27                       1
25     0           127       27                       1
26     0            78       27                       1
27     0            48       27                       1
28     1            60       27                       1
29     0            77       27                       1
30     0            99       27                       1
⋮      ⋮           ⋮         ⋮                        ⋮
119181 0           195       35                       29
119182 0           100       35                       31
119183 0           198       35                       29
119184 0           212       35                       28
119185 0           212       35                       28
119186 0            54       35                       27
119187 0           210       35                       28
119188 0           212       35                       28
119189 0           261       35                       30
119190 0           207       34                       25
119191 0           201       35                       30
119192 0           175       35                       31
119193 0           175       35                       31
119194 0           175       35                       31
119195 0           201       35                       29
119196 0           200       35                       30
119197 0           165       35                       29
119198 0           185       35                       30
119199 0           247       35                       31
119200 0           109       35                       31
119201 0            44       35                       31
119202 0           188       35                       31
119203 0           135       35                       30
119204 0           164       35                       31
119205 0            21       35                       30
119206 0            23       35                       30
119207 0           102       35                       31
119208 0            34       35                       31
119209 0           109       35                       31
119210 0           205       35                       29
       arrival_date_month stays_in_weekend_nights stays_in_week_nights adults
1      7                  0                       0                    2
2      7                  0                       0                    2
3      7                  0                       1                    1
4      7                  0                       1                    1
5      7                  0                       2                    2
6      7                  0                       2                    2
7      7                  0                       2                    2
8      7                  0                       2                    2
9      7                  0                       3                    2
10     7                  0                       3                    2
11     7                  0                       4                    2
12     7                  0                       4                    2
13     7                  0                       4                    2
14     7                  0                       4                    2
15     7                  0                       4                    2
16     7                  0                       4                    2
17     7                  0                       4                    2
18     7                  0                       1                    2
19     7                  0                       1                    2
20     7                  0                       4                    2
21     7                  1                       4                    1
22     7                  2                       4                    2
23     7                  2                       4                    2
24     7                  2                       4                    2
25     7                  2                       5                    2
26     7                  2                       5                    2
27     7                  2                       5                    2
28     7                  2                       5                    2
29     7                  2                       5                    2
30     7                  2                       5                    2
⋮      ⋮                  ⋮                       ⋮                    ⋮
119181 8                  1                       5                    2
119182 8                  1                       3                    2
119183 8                  1                       5                    2
119184 8                  2                       5                    2
119185 8                  2                       5                    2
119186 8                  3                       5                    1
119187 8                  2                       5                    2
119188 8                  2                       5                    2
119189 8                  1                       4                    2
119190 8                  3                       7                    2
119191 8                  1                       4                    1
119192 8                  1                       3                    2
119193 8                  1                       3                    1
119194 8                  1                       3                    1
119195 8                  1                       5                    2
119196 8                  1                       4                    2
119197 8                  1                       5                    3
119198 8                  1                       4                    2
119199 8                  1                       3                    2
119200 8                  1                       3                    2
119201 8                  1                       3                    2
119202 8                  2                       3                    2
119203 8                  2                       4                    3
119204 8                  2                       4                    2
119205 8                  2                       5                    2
119206 8                  2                       5                    2
119207 8                  2                       5                    3
119208 8                  2                       5                    2
119209 8                  2                       5                    2
119210 8                  2                       7                    2
       children babies ⋯ reserved_room_type_G reserved_room_type_H
1      0        0      ⋯ 0                    0
2      0        0      ⋯ 0                    0
3      0        0      ⋯ 0                    0
4      0        0      ⋯ 0                    0
5      0        0      ⋯ 0                    0
6      0        0      ⋯ 0                    0
7      0        0      ⋯ 0                    0
8      0        0      ⋯ 0                    0
9      0        0      ⋯ 0                    0
10     0        0      ⋯ 0                    0
11     0        0      ⋯ 0                    0
12     0        0      ⋯ 0                    0
13     0        0      ⋯ 0                    0
14     1        0      ⋯ 1                    0
15     0        0      ⋯ 0                    0
16     0        0      ⋯ 0                    0
17     0        0      ⋯ 0                    0
18     0        0      ⋯ 0                    0
19     0        0      ⋯ 0                    0
20     0        0      ⋯ 1                    0
21     0        0      ⋯ 0                    0
22     0        0      ⋯ 0                    0
23     0        0      ⋯ 0                    0
24     0        0      ⋯ 0                    0
25     0        0      ⋯ 0                    0
26     0        0      ⋯ 0                    0
27     0        0      ⋯ 0                    0
28     0        0      ⋯ 0                    0
29     0        0      ⋯ 0                    0
30     0        0      ⋯ 0                    0
⋮      ⋮        ⋮      ⋱ ⋮                    ⋮
119181 0        0      ⋯ 0                    0
119182 0        0      ⋯ 0                    0
119183 0        0      ⋯ 0                    0
119184 0        0      ⋯ 0                    0
119185 0        0      ⋯ 0                    0
119186 0        0      ⋯ 1                    0
119187 0        0      ⋯ 0                    0
119188 0        0      ⋯ 0                    0
119189 0        0      ⋯ 0                    0
119190 0        0      ⋯ 0                    0
119191 0        0      ⋯ 0                    0
119192 0        0      ⋯ 0                    0
119193 0        0      ⋯ 0                    0
119194 0        0      ⋯ 0                    0
119195 0        0      ⋯ 0                    0
119196 0        0      ⋯ 0                    0
119197 0        0      ⋯ 0                    0
119198 0        0      ⋯ 0                    0
119199 0        0      ⋯ 0                    0
119200 0        0      ⋯ 0                    0
119201 0        0      ⋯ 0                    0
119202 0        0      ⋯ 0                    0
119203 0        0      ⋯ 1                    0
119204 0        0      ⋯ 0                    0
119205 0        0      ⋯ 0                    0
119206 0        0      ⋯ 0                    0
119207 0        0      ⋯ 0                    0
119208 0        0      ⋯ 0                    0
119209 0        0      ⋯ 0                    0
119210 0        0      ⋯ 0                    0
       reserved_room_type_L deposit_type_No_Deposit deposit_type_Non_Refund
1      0                    1                       0
2      0                    1                       0
3      0                    1                       0
4      0                    1                       0
5      0                    1                       0
6      0                    1                       0
7      0                    1                       0
8      0                    1                       0
9      0                    1                       0
10     0                    1                       0
11     0                    1                       0
12     0                    1                       0
13     0                    1                       0
14     0                    1                       0
15     0                    1                       0
16     0                    1                       0
17     0                    1                       0
18     0                    1                       0
19     0                    1                       0
20     0                    1                       0
21     0                    1                       0
22     0                    1                       0
23     0                    1                       0
24     0                    1                       0
25     0                    1                       0
26     0                    1                       0
27     0                    1                       0
28     0                    1                       0
29     0                    1                       0
30     0                    1                       0
⋮      ⋮                    ⋮                       ⋮
119181 0                    1                       0
119182 0                    1                       0
119183 0                    1                       0
119184 0                    1                       0
119185 0                    1                       0
119186 0                    1                       0
119187 0                    1                       0
119188 0                    1                       0
119189 0                    1                       0
119190 0                    1                       0
119191 0                    1                       0
119192 0                    1                       0
119193 0                    1                       0
119194 0                    1                       0
119195 0                    1                       0
119196 0                    1                       0
119197 0                    1                       0
119198 0                    1                       0
119199 0                    1                       0
119200 0                    1                       0
119201 0                    1                       0
119202 0                    1                       0
119203 0                    1                       0
119204 0                    1                       0
119205 0                    1                       0
119206 0                    1                       0
119207 0                    1                       0
119208 0                    1                       0
119209 0                    1                       0
119210 0                    1                       0
       deposit_type_Refundable customer_type_Contract customer_type_Group
1      0                       0                      0
2      0                       0                      0
3      0                       0                      0
4      0                       0                      0
5      0                       0                      0
6      0                       0                      0
7      0                       0                      0
8      0                       0                      0
9      0                       0                      0
10     0                       0                      0
11     0                       0                      0
12     0                       0                      0
13     0                       0                      0
14     0                       0                      0
15     0                       0                      0
16     0                       0                      0
17     0                       1                      0
18     0                       0                      0
19     0                       0                      0
20     0                       0                      0
21     0                       0                      0
22     0                       0                      0
23     0                       0                      0
24     0                       0                      0
25     0                       1                      0
26     0                       0                      0
27     0                       1                      0
28     0                       0                      0
29     0                       0                      0
30     0                       0                      0
⋮      ⋮                       ⋮                      ⋮
119181 0                       0                      0
119182 0                       0                      0
119183 0                       0                      0
119184 0                       0                      0
119185 0                       0                      0
119186 0                       0                      0
119187 0                       0                      0
119188 0                       0                      0
119189 0                       0                      0
119190 0                       0                      0
119191 0                       0                      0
119192 0                       0                      0
119193 0                       0                      0
119194 0                       0                      0
119195 0                       0                      0
119196 0                       0                      0
119197 0                       0                      0
119198 0                       0                      0
119199 0                       0                      0
119200 0                       0                      0
119201 0                       0                      0
119202 0                       0                      0
119203 0                       0                      0
119204 0                       0                      0
119205 0                       0                      0
119206 0                       0                      0
119207 0                       0                      0
119208 0                       0                      0
119209 0                       0                      0
119210 0                       0                      0
       customer_type_Transient customer_type_Transient-Party
1      1                       0
2      1                       0
3      1                       0
4      1                       0
5      1                       0
6      1                       0
7      1                       0
8      1                       0
9      1                       0
10     1                       0
11     1                       0
12     1                       0
13     1                       0
14     1                       0
15     1                       0
16     1                       0
17     0                       0
18     1                       0
19     1                       0
20     1                       0
21     1                       0
22     1                       0
23     1                       0
24     1                       0
25     0                       0
26     1                       0
27     0                       0
28     1                       0
29     1                       0
30     1                       0
⋮      ⋮                       ⋮
119181 1                       0
119182 1                       0
119183 1                       0
119184 1                       0
119185 1                       0
119186 1                       0
119187 1                       0
119188 1                       0
119189 1                       0
119190 1                       0
119191 1                       0
119192 1                       0
119193 1                       0
119194 1                       0
119195 1                       0
119196 1                       0
119197 1                       0
119198 1                       0
119199 1                       0
119200 1                       0
119201 1                       0
119202 1                       0
119203 1                       0
119204 1                       0
119205 1                       0
119206 1                       0
119207 1                       0
119208 1                       0
119209 1                       0
119210 1                       0

### read.table() function

Similar to `read_csv` you can also use the `read.table` function to load the file. Make sure you are adding delimiter “,” and header = 1. It will set the first row as column names instead of “V1”, “V2”,...

In [24]:
data2 <- read.table('hotel_bookings_clean.csv', sep=",", header = 1)
head(data2, 5)

  is_canceled lead_time arrival_date_week_number arrival_date_day_of_month
1 0           342       27                       1
2 0           737       27                       1
3 0             7       27                       1
4 0            13       27                       1
5 0            14       27                       1
  arrival_date_month stays_in_weekend_nights stays_in_week_nights adults
1 7                  0                       0                    2
2 7                  0                       0                    2
3 7                  0                       1                    1
4 7                  0                       1                    1
5 7                  0                       2                    2
  children babies ⋯ reserved_room_type_G reserved_room_type_H
1 0        0      ⋯ 0                    0
2 0        0      ⋯ 0                    0
3 0        0      ⋯ 0                    0
4 0        0      ⋯ 0                    0
5 0        0      ⋯ 0                    0
  reserved_room_type_L deposit_type_No_Deposit deposit_type_Non_Refund
1 0                    1                       0
2 0                    1                       0
3 0                    1                       0
4 0                    1                       0
5 0                    1                       0
  deposit_type_Refundable customer_type_Contract customer_type_Group
1 0                       0                      0
2 0                       0                      0
3 0                       0                      0
4 0                       0                      0
5 0                       0                      0
  customer_type_Transient customer_type_Transient.Party
1 1                       0
2 1                       0
3 1                       0
4 1                       0
5 1                       0

### Comparing the timing of these functions

In [28]:
timing_result <- system.time({
    data1 <- read_csv('hotel_bookings_clean.csv', show_col_types = FALSE)
})

# Print the result and timing information
print(timing_result)

   user  system elapsed
  0.629   0.039   0.122

In [27]:
timing_result <- system.time({
    data_tab <- read_delim('hotel_bookings_clean.csv', delim = ',', show_col_types = FALSE)
})

# Print the result and timing information
print(timing_result)

   user  system elapsed
  0.647   0.037   0.117

In [26]:
timing_result <- system.time({
    data2 <- read.table('hotel_bookings_clean.csv', sep=",", header = 1)
})

# Print the result and timing information
print(timing_result)

   user  system elapsed
  0.547   0.011   0.559

## Importing a TXT file in R

In this part, we will use the Canserbero Lyrics dataset to load a text file. The file consists of Lyrics from the rapper Canserbero. We can use the `readLines` function to load the simple file, but we have to perform additional tasks to convert it into a dataframe.

We will use read.table’s alternative function, `read.delim` to load the text file as an R dataframe. Other read.table’s alternative functions are read.csv, read.csv2, and read.delim2.

In [29]:
data3 <- read.delim('Canserbero_lyrics.txt',header = F)
head(data3, 5)

  V1
1 Como el segundo que ya transcurrió
2 Como en el que oíste mi frase anterior
3 Y ahora mi frase anterior es frase anterior
4 Y ahora, ambas son recuerdos
5 Podrás actuar igual un minuto después

## Importing data from Excel into R

We will use the readxl package’s `read_excel` function to read a single sheet from an Excel file. The package comes with tiddyvers, but it is not the core part of it, so we need to load the package before using the function. 

The function requires the location of the data and sheet number. We can also modify how our dataframe looks by reading the description of other parameters in read_excel documentation.

In [32]:
library(readxl)
data4 <- read_excel("hotel_bookings_clean.xlsx", sheet = 1, col_names = TRUE)
head(data4, 5)

  is_canceled lead_time arrival_date_week_number arrival_date_day_of_month
1 0           342       27                       1
2 0           737       27                       1
3 0             7       27                       1
4 0            13       27                       1
5 0            14       27                       1
  arrival_date_month stays_in_weekend_nights stays_in_week_nights adults
1 7                  0                       0                    2
2 7                  0                       0                    2
3 7                  0                       1                    1
4 7                  0                       1                    1
5 7                  0                       2                    2
  children babies ⋯ reserved_room_type_G reserved_room_type_H
1 0.0      0      ⋯ 0                    0
2 0.0      0      ⋯ 0                    0
3 0.0      0      ⋯ 0                    0
4 0.0      0      ⋯ 0                    0
5 0.0      0      ⋯ 0                    0
  reserved_room_type_L deposit_type_No_Deposit deposit_type_Non_Refund
1 0                    1                       0
2 0                    1                       0
3 0                    1                       0
4 0                    1                       0
5 0                    1                       0
  deposit_type_Refundable customer_type_Contract customer_type_Group
1 0                       0                      0
2 0                       0                      0
3 0                       0                      0
4 0                       0                      0
5 0                       0                      0
  customer_type_Transient customer_type_Transient-Party
1 1                       0
2 1                       0
3 1                       0
4 1                       0
5 1                       0

In [31]:
?read_excel()